### PR TITLE
Support Winget package upgrades

### LINKED ISSUE #6: Support upgrade commands
I checked the .ps1 file and couldn't find the upgrade commands there, it would be nice to have them.
Great initiative, by the way.

### PR DESCRIPTION
**Pull request by ethanbergstrom**

### CODE REVIEW

**Comment by giggio** [comment]
Great! Are you planning on a way of listing available upgrades, like running only `winget upgrade`?
My scenario is adding a script to run upgrade only on some packages, as we don't have a way to pin packages yet with winget. I'll keep a list of the pinned packages somewhere in a file, get all the available upgrades and discard the ones I "pinned".

**Comment by ethanbergstrom** [comment]
@giggio my recommendation in that scenario would be to regularly run ``Update-WinGetPackage -ID $package``, perhaps piping it an array of package names, to only upgrade the packages that you deem safe to upgrade. 

If no package upgrade is available / the package is already up to date, my expectation is that nothing will return, but no error will be thrown either.

**Comment by giggio** [comment]
That would work, but it would also take longer, as it will go through packages that don't have an upgrade available. Running only `winget upgrade` without parameters shows only the available upgrades.

**Comment by ethanbergstrom** [comment]
It takes hardly any time, so am not concerned. 

Winget is a pain in the butt to parse output for, and I don't have any intention on re-writing the output handler to support a `Get-WinGetPackageUpgrade` use case.

**Comment by giggio** [comment]
Yes, it is true. I tried parsing it with `awk` and it fails miserably. They should have a parser friendly output, either with tabs, json or whatever.
It feels like they are don't want us to build upon it.

**Comment by ethanbergstrom** [comment]
Most of the time on this was spent figuring out why tests ran so long on GitHub Actions - turns out GitHub installs a lot of stuff on their images that winget spends a lot of time trying (and failing) to upgrade vs. what I was seeing in my Windows Sandbox environment. 

As a result, the `-all` switch **does** work, but it doesn't have test coverage. Your results may vary.

**Comment by ethanbergstrom** [comment]
> My scenario is adding a script to run upgrade only on some packages, as we don't have a way to pin packages yet with winget. I'll keep a list of the pinned packages somewhere in a file, get all the available upgrades and discard the ones I "pinned".

If your goal is to continually keep certain packages up-to-date, while to keep others pinned to a specific version, I might recommend checking out my WinGet provider for PackageManagement (which, in turn, leverages Cobalt), that is compatible with various configuration management frameworks, including [PowerShell DSC](https://docs.microsoft.com/en-us/powershell/dsc/reference/resources/packagemanagement/packagemanagementdscresource?view=dsc-1.1) for a pure-PowerShell implementation. 

See https://gist.github.com/ethanbergstrom/9a4a0d29ea0452ef46bba580a7567d98 for a working example of using DSC to check and automatically 'correct'/update (if desired) a set of WinGet packages every 24 hours.

**Pull request merged**
